/*
Highly divisible triangular number
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProblemSolver.src
{
    class Problem012 : SolvedProblems
    {
        public override void Solve() //3.082s
        {
            ulong tri = 0;
            int numOfDivisors = 1;
            
            for (ulong i = 1; numOfDivisors < 500; i++){

                numOfDivisors = 1;
                tri += i;

                for (ulong n = 1; n <= Math.Sqrt(tri); n++){
                    if(tri % n == 0){
                        numOfDivisors += 1;
                    }
                }

            numOfDivisors = (numOfDivisors - 1) * 2;
        
            }
            EulerHelper.printAns(tri.ToString());
        }
    }
}
