/*
Triangular, pentagonal, and hexagonal
Problem 45
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Numerics;

namespace ProblemSolver.src
{
    class Problem045 : SolvedProblems
    {
        public override void Solve()
        {
            Dictionary<BigInteger, BigInteger> triangles = EulerHelper.triangleNums(100000);
            Dictionary<BigInteger, BigInteger> pentagons = EulerHelper.pentagonalNums(100000);
            Dictionary<BigInteger, BigInteger> hexagons = EulerHelper.hexagonalNums(100000);

            BigInteger triNum = 0;
            BigInteger counter = 286;

            while (triNum == 0)
            {
                if (counter > triangles.Count)
                {
                    break;
                }

                if (pentagons.ContainsValue(triangles[counter]) && hexagons.ContainsValue(triangles[counter]))
                {
                    triNum = triangles[counter];
                }
                
                counter++;
            }

            EulerHelper.printAns(triNum.ToString());

        }
    }
}
